// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: news/v1/service.proto

package newsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Newsservice_CreateNews_FullMethodName = "/news.v1.Newsservice/CreateNews"
	Newsservice_GetNews_FullMethodName    = "/news.v1.Newsservice/GetNews"
)

// NewsserviceClient is the client API for Newsservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsserviceClient interface {
	CreateNews(ctx context.Context, in *NewsRequest, opts ...grpc.CallOption) (*NewsResponse, error)
	GetNews(ctx context.Context, in *NewsId, opts ...grpc.CallOption) (*NewsResponse, error)
}

type newsserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsserviceClient(cc grpc.ClientConnInterface) NewsserviceClient {
	return &newsserviceClient{cc}
}

func (c *newsserviceClient) CreateNews(ctx context.Context, in *NewsRequest, opts ...grpc.CallOption) (*NewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsResponse)
	err := c.cc.Invoke(ctx, Newsservice_CreateNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsserviceClient) GetNews(ctx context.Context, in *NewsId, opts ...grpc.CallOption) (*NewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsResponse)
	err := c.cc.Invoke(ctx, Newsservice_GetNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsserviceServer is the server API for Newsservice service.
// All implementations must embed UnimplementedNewsserviceServer
// for forward compatibility.
type NewsserviceServer interface {
	CreateNews(context.Context, *NewsRequest) (*NewsResponse, error)
	GetNews(context.Context, *NewsId) (*NewsResponse, error)
	mustEmbedUnimplementedNewsserviceServer()
}

// UnimplementedNewsserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewsserviceServer struct{}

func (UnimplementedNewsserviceServer) CreateNews(context.Context, *NewsRequest) (*NewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNews not implemented")
}
func (UnimplementedNewsserviceServer) GetNews(context.Context, *NewsId) (*NewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNews not implemented")
}
func (UnimplementedNewsserviceServer) mustEmbedUnimplementedNewsserviceServer() {}
func (UnimplementedNewsserviceServer) testEmbeddedByValue()                     {}

// UnsafeNewsserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsserviceServer will
// result in compilation errors.
type UnsafeNewsserviceServer interface {
	mustEmbedUnimplementedNewsserviceServer()
}

func RegisterNewsserviceServer(s grpc.ServiceRegistrar, srv NewsserviceServer) {
	// If the following call pancis, it indicates UnimplementedNewsserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Newsservice_ServiceDesc, srv)
}

func _Newsservice_CreateNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsserviceServer).CreateNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Newsservice_CreateNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsserviceServer).CreateNews(ctx, req.(*NewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Newsservice_GetNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewsId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsserviceServer).GetNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Newsservice_GetNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsserviceServer).GetNews(ctx, req.(*NewsId))
	}
	return interceptor(ctx, in, info, handler)
}

// Newsservice_ServiceDesc is the grpc.ServiceDesc for Newsservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Newsservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "news.v1.Newsservice",
	HandlerType: (*NewsserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNews",
			Handler:    _Newsservice_CreateNews_Handler,
		},
		{
			MethodName: "GetNews",
			Handler:    _Newsservice_GetNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "news/v1/service.proto",
}
